services:
  - type: web
    name: soltxd
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d2gnupvdiees73dngcs0-a.oregon-postgres.render.com/soltxddb_a0dn
      - key: DB_USER
        value: santod
      - key: DB_PASSWORD
        value: NuZJ7Za99pVEQnUxdEyJCbbe7KzLwWQY
		

		